
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexk
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    ArrayList<Cliente> ListaCliente = new ArrayList();
    ArrayList<Pizza> ListaPizzas = new ArrayList();
    double preciototal = 0;

    public principal() {
        initComponents();

        DefaultListModel lm = new DefaultListModel();

        ListaPedidosGrafico.setModel(lm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTamanos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNombreCliente = new javax.swing.JTextField();
        tDireccionCliente = new javax.swing.JTextField();
        tEmailCliente = new javax.swing.JTextField();
        bGuardaCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ListaDePizzasGrafico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bAnadirPizza = new javax.swing.JButton();
        bBorrarPizza = new javax.swing.JButton();
        bBorrarPedido = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bEnviarPedido = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPedidosGrafico = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Pizzería");

        jLabel2.setText("Nombre");

        jLabel3.setText("Dirección");

        jLabel4.setText("Email");

        bGuardaCliente.setText("Guardar Cliente");
        bGuardaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardaClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Elige tu pizza");

        ListaDePizzasGrafico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BBQ", "Carbonara", "4 Quesos" }));

        jLabel6.setText("Tamaño");

        jLabel7.setText("Toppings 2€");

        grupoTamanos.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Pequeña 5€");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        grupoTamanos.add(jRadioButton2);
        jRadioButton2.setText("Mediana 7.5€");

        grupoTamanos.add(jRadioButton3);
        jRadioButton3.setText("Familiar 10€");

        jCheckBox1.setText("Extra Cebolla");

        jCheckBox2.setText("Extra Queso");

        jCheckBox3.setText("Extra Piña");

        jLabel8.setText("Precio");

        jLabel9.setText("Tu Pedido");

        bAnadirPizza.setText("Añadir Pizza");
        bAnadirPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirPizzaActionPerformed(evt);
            }
        });

        bBorrarPizza.setText("Borrar Pizza");
        bBorrarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarPizzaActionPerformed(evt);
            }
        });

        bBorrarPedido.setText("Borrar Pedido");
        bBorrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarPedidoActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bEnviarPedido.setText("Enviar Pedido");
        bEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarPedidoActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jScrollPane2.setViewportView(ListaPedidosGrafico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(ListaDePizzasGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tEmailCliente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(bGuardaCliente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(144, 144, 144))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton3))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jLabel7)
                                            .addComponent(jCheckBox1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(bEnviarPedido)
                                        .addGap(54, 54, 54)
                                        .addComponent(bSalir)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(bAnadirPizza)
                                        .addGap(37, 37, 37)
                                        .addComponent(bBorrarPizza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bBorrarPedido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ListaDePizzasGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGuardaCliente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jCheckBox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jCheckBox3)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAnadirPizza)
                        .addComponent(bBorrarPizza)
                        .addComponent(bBorrarPedido))
                    .addComponent(bSalir)
                    .addComponent(bEnviarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardaClienteActionPerformed

        String nombre = tNombreCliente.getText();
        String direccion = tDireccionCliente.getText();
        String email = tEmailCliente.getText();

        Cliente c = new Cliente(nombre, direccion, email);
        ListaCliente.add(c);

        tNombreCliente.setEnabled(false);
        tDireccionCliente.setEnabled(false);
        tEmailCliente.setEnabled(false);

        JOptionPane.showMessageDialog(this, "Cliente añadido con éxito");


    }//GEN-LAST:event_bGuardaClienteActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    private void bAnadirPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirPizzaActionPerformed
        tPrecio.setEditable(false);
        DefaultListModel lm = new DefaultListModel();

        String tipo = ListaDePizzasGrafico.getSelectedItem().toString();
        String tamano = "";
        double precio = 0;

        String topings = "";
        if (jRadioButton1.isSelected()) {
            tamano = "Pequeña";
            precio = precio + 5;
        } else if (jRadioButton2.isSelected()) {
            tamano = "Mediana";
            precio = precio + 7.5;
        } else if (jRadioButton3.isSelected()) {
            tamano = "Familiar";
            precio = precio + 10;
        }

        if (jCheckBox1.isSelected()) {
            precio = precio + 2;
            topings = topings + " Extra Cebolla ";
        }
        if (jCheckBox2.isSelected()) {
            precio = precio + 2;
            topings = topings + " Extra Queso ";
        }
        if (jCheckBox3.isSelected()) {
            precio = precio + 2;
            topings = topings + " Extra Piña ";
        }

        Pizza pizza = new Pizza(tipo, tamano, topings, precio);
        ListaPizzas.add(pizza);
        preciototal = preciototal + pizza.getPrecio();
        tPrecio.setText("" + preciototal);
        ListaPedidosGrafico.setModel(lm);

        for (int i = 0; i < ListaPizzas.size(); i++) {
            lm.addElement(ListaPizzas.get(i).toString());

        }

        JOptionPane.showMessageDialog(this, "Pizza añadida con éxito");


    }//GEN-LAST:event_bAnadirPizzaActionPerformed

    private void bEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarPedidoActionPerformed
        Pedido p = new Pedido(ListaCliente.get(0), ListaPizzas);
        JOptionPane.showMessageDialog(this, "Pedido enviado con éxito, está en el horno!");


    }//GEN-LAST:event_bEnviarPedidoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBorrarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarPizzaActionPerformed

        ListaPizzas.remove(ListaPedidosGrafico.getSelectedIndex());

        JOptionPane.showMessageDialog(this, "Pizza eliminada");


    }//GEN-LAST:event_bBorrarPizzaActionPerformed

    private void bBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarPedidoActionPerformed

        tNombreCliente.setEnabled(true);
        tDireccionCliente.setEnabled(true);
        tEmailCliente.setEnabled(true);
        ListaPizzas.removeAll(ListaPizzas);
        ListaCliente.removeAll(ListaCliente);
        ListaPedidosGrafico.removeAll();
        preciototal = 0;
        JOptionPane.showMessageDialog(this, "Pedido eliminado");


    }//GEN-LAST:event_bBorrarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaDePizzasGrafico;
    private javax.swing.JList<String> ListaPedidosGrafico;
    private javax.swing.JButton bAnadirPizza;
    private javax.swing.JButton bBorrarPedido;
    private javax.swing.JButton bBorrarPizza;
    private javax.swing.JButton bEnviarPedido;
    private javax.swing.JButton bGuardaCliente;
    private javax.swing.JButton bSalir;
    private javax.swing.ButtonGroup grupoTamanos;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tDireccionCliente;
    private javax.swing.JTextField tEmailCliente;
    private javax.swing.JTextField tNombreCliente;
    private javax.swing.JTextField tPrecio;
    // End of variables declaration//GEN-END:variables
}
