
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexk
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoLetras = new javax.swing.ButtonGroup();
        GrupoColores = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vNegrita = new javax.swing.JRadioButton();
        vCursiva = new javax.swing.JRadioButton();
        vNormal = new javax.swing.JRadioButton();
        vVerde = new javax.swing.JRadioButton();
        vAzul = new javax.swing.JRadioButton();
        vTexto = new javax.swing.JLabel();
        bBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estilos de letra");

        jLabel2.setText("Color");

        GrupoLetras.add(vNegrita);
        vNegrita.setText("Negrita");
        vNegrita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vNegritaMouseClicked(evt);
            }
        });
        vNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNegritaActionPerformed(evt);
            }
        });

        GrupoLetras.add(vCursiva);
        vCursiva.setText("Cursiva");
        vCursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCursivaActionPerformed(evt);
            }
        });

        GrupoLetras.add(vNormal);
        vNormal.setText("Normal");
        vNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNormalActionPerformed(evt);
            }
        });

        GrupoColores.add(vVerde);
        vVerde.setText("Verde");
        vVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVerdeActionPerformed(evt);
            }
        });

        GrupoColores.add(vAzul);
        vAzul.setText("Azul");
        vAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAzulActionPerformed(evt);
            }
        });

        vTexto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        vTexto.setText("BOTONES DE OPCION");

        bBoton.setText("Salir");
        bBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vNegrita)
                            .addComponent(vNormal)
                            .addComponent(vCursiva))
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vVerde)
                            .addComponent(vAzul))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(vTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bBoton)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vNegrita)
                    .addComponent(vVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vAzul)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vCursiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vNormal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBoton)
                    .addComponent(vTexto))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBotonActionPerformed
        System.exit(0);


    }//GEN-LAST:event_bBotonActionPerformed


    private void vNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNegritaActionPerformed

        Font Negrita = new Font("Dialog", Font.BOLD, 24);
        vTexto.setFont(Negrita);


    }//GEN-LAST:event_vNegritaActionPerformed

    private void vNegritaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vNegritaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vNegritaMouseClicked

    private void vCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCursivaActionPerformed
        Font Cursiva = new Font("Dialog", Font.ITALIC, 24);
        vTexto.setFont(Cursiva);
    }//GEN-LAST:event_vCursivaActionPerformed

    private void vNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNormalActionPerformed
        Font Normal = new Font("Dialog", Font.PLAIN, 24);
        vTexto.setFont(Normal);
    }//GEN-LAST:event_vNormalActionPerformed

    private void vVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVerdeActionPerformed
        vTexto.setForeground(Color.green);
    }//GEN-LAST:event_vVerdeActionPerformed

    private void vAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAzulActionPerformed
        vTexto.setForeground(Color.blue);
    }//GEN-LAST:event_vAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoColores;
    private javax.swing.ButtonGroup GrupoLetras;
    private javax.swing.JButton bBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton vAzul;
    private javax.swing.JRadioButton vCursiva;
    private javax.swing.JRadioButton vNegrita;
    private javax.swing.JRadioButton vNormal;
    private javax.swing.JLabel vTexto;
    private javax.swing.JRadioButton vVerde;
    // End of variables declaration//GEN-END:variables
}
