
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.Default;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexk
 */
public class Aplicacion extends javax.swing.JFrame {

    String aux = "";
    DefaultListModel ModelAlquiler = new DefaultListModel();
    DefaultListModel ModelPeliculas = new DefaultListModel();
    DefaultListModel ModelClientes = new DefaultListModel();

    /**
     *
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        //Creacion Clientes
        Cliente Juan = new Cliente("Juan Martínez", "22.365.369-F");
        Cliente Pedro = new Cliente("Pedro Garre", "25.325.789-D");
        Cliente Lucas = new Cliente("Lucas Fernández", "“15.852.741-R");

        //Creacion Peliculas
        Pelicula Cien = new Pelicula("Cien años de perdón", "thriller");
        Pelicula deadpool = new Pelicula("Deadpool", "acción");
        Pelicula zootropolis = new Pelicula("Zootrópolis", "animación");
        Pelicula habitacion = new Pelicula("La habitación", "drama");
        Pelicula spotlight = new Pelicula("Spotlight", "thriller");
        Pelicula renacido = new Pelicula("El renacido", "acción");
        //Añado Todas las pelis a la gran lista de peliculas

        listapeliculas.setModel(ModelPeliculas);
        ModelPeliculas.addElement(Cien.toString2());
        ModelPeliculas.addElement(deadpool.toString2());
        ModelPeliculas.addElement(zootropolis.toString2());
        ModelPeliculas.addElement(habitacion.toString2());
        ModelPeliculas.addElement(spotlight.toString2());
        ModelPeliculas.addElement(renacido.toString2());

        //Lista Visual de Clientes
        listaclientes.setModel(ModelClientes);
        ModelClientes.addElement(Juan.toString2());
        ModelClientes.addElement(Pedro.toString2());
        ModelClientes.addElement(Lucas.toString2());

        //Añadims Pelis Dispnibles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaclientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listapeliculas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaalquileres = new javax.swing.JList<>();
        bAlquilar = new javax.swing.JButton();
        bDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clientes");

        jLabel2.setText("Peliculas");

        jLabel3.setText("Lista Alquileres");

        jScrollPane1.setViewportView(listaclientes);

        jScrollPane2.setViewportView(listapeliculas);

        jScrollPane3.setViewportView(listaalquileres);

        bAlquilar.setText("Alquilar");
        bAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlquilarActionPerformed(evt);
            }
        });

        bDevolver.setText("Devolver");
        bDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(bAlquilar))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(bDevolver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bAlquilar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDevolver)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlquilarActionPerformed

        listaalquileres.setModel(ModelAlquiler);
        aux = listapeliculas.getSelectedValue();
        /*
        c = "" + listaclientes.getSelectedValue() + " - " + listapeliculas.getSelectedValue();
        ModelAlquiler.addElement(c);
        ModelPeliculas.remove(listapeliculas.getSelectedIndex()); */
 /*
        
        Alquiler c = new Alquiler(listapeliculas.getSelectedValue(),listaclientes.getSelectedValue());
        ModelAlquiler.addElement(c.toString2());
         */
        Pelicula c = new Pelicula();
        Cliente e = new Cliente();
        e.Alquilar(listapeliculas.getSelectedValue());
        c.Disponibles(listapeliculas.getSelectedValue());
        ModelAlquiler.addElement(listaclientes.getSelectedValue() + " - " + e.MostrarPelisAlquiladas());
        ModelPeliculas.remove(listapeliculas.getSelectedIndex());

    }//GEN-LAST:event_bAlquilarActionPerformed

    private void bDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDevolverActionPerformed
        ModelAlquiler.remove(listaalquileres.getSelectedIndex());

        
        
        

    }//GEN-LAST:event_bDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlquilar;
    private javax.swing.JButton bDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaalquileres;
    private javax.swing.JList<String> listaclientes;
    private javax.swing.JList<String> listapeliculas;
    // End of variables declaration//GEN-END:variables
}
