/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio15;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alexk
 */
public class Ejercicio15 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio15
     */
    public Ejercicio15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruta1Button = new javax.swing.JButton();
        ruta2Button = new javax.swing.JButton();
        ruta3Button = new javax.swing.JButton();
        labelruta1 = new javax.swing.JLabel();
        labelruta2 = new javax.swing.JLabel();
        labelruta3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ruta1Button.setText("Crea Fichero1");
        ruta1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta1ButtonActionPerformed(evt);
            }
        });

        ruta2Button.setText("Crea Fichero2");
        ruta2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta2ButtonActionPerformed(evt);
            }
        });

        ruta3Button.setText("Crea Fichero3");
        ruta3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta3ButtonActionPerformed(evt);
            }
        });

        labelruta1.setText("RutaFichero1");

        labelruta2.setText("RutaFichero2");

        labelruta3.setText("RutaFichero3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ruta3Button)
                    .addComponent(ruta2Button)
                    .addComponent(ruta1Button))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelruta1)
                    .addComponent(labelruta2)
                    .addComponent(labelruta3))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta1Button)
                    .addComponent(labelruta1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta2Button)
                    .addComponent(labelruta2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta3Button)
                    .addComponent(labelruta3))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruta1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta1ButtonActionPerformed

        FileDialog fd = new FileDialog(this, "Selecciona un fichero", FileDialog.SAVE);
        fd.setDirectory("C:\\");
        fd.setFile("*.txt");
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();
        labelruta1.setText(filename);

        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            fw = new FileWriter(filename);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < 100; i++) {
                int aleatorio = (int) (Math.random() * 100) + 1;
                bw.write("" + aleatorio);
                bw.newLine();
            }

        } catch (IOException ex) {
            Logger.getLogger(Ejercicio15.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (bw != null) {
                    bw.close();
                }

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_ruta1ButtonActionPerformed

    private void ruta2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta2ButtonActionPerformed

        FileDialog fd = new FileDialog(this, "Selecciona un fichero", FileDialog.SAVE);
        fd.setDirectory("C:\\");
        fd.setFile("*.bin");
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();
        labelruta2.setText(filename);

        FileOutputStream fos = null;
        DataOutputStream dos = null;
        try {
            fos = new FileOutputStream(filename);
            dos = new DataOutputStream(fos);

            for (int i = 0; i < 100; i++) {
                int aleatorio = (int) (Math.random() * 100) + 1;

                dos.writeInt(aleatorio);

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ejercicio15.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ejercicio15.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ruta2ButtonActionPerformed

    private void ruta3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta3ButtonActionPerformed

        FileDialog fd = new FileDialog(this, "Selecciona un fichero de Texto", FileDialog.LOAD);
        fd.setDirectory("C:\\");
        fd.setFile("*.txt");
        fd.setVisible(true);
        String filenameTexto = fd.getDirectory() + fd.getFile();

        FileDialog fd2 = new FileDialog(this, "Selecciona un fichero Binario", FileDialog.LOAD);
        fd.setDirectory("C:\\");
        fd.setFile("*.bin");
        fd.setVisible(true);
        String filenameBinario = fd.getDirectory() + fd.getFile();

        FileDialog fd3 = new FileDialog(this, "Selecciona un fichero", FileDialog.SAVE);
        fd.setDirectory("C:\\");
        fd.setFile("*.txt");
        fd.setVisible(true);
        String filenameFinal = fd.getDirectory() + fd.getFile();
        labelruta3.setText(filenameFinal);

        FileReader fr = null;
        BufferedReader br = null;

        FileInputStream fis = null;
        DataInputStream dis = null;

        FileWriter fw = null;
        BufferedWriter bw = null;

        ArrayList<String> ListaFicheroTexto = new ArrayList();
        ArrayList<String> ListaFicheroBinario = new ArrayList();
        String linea;
        int n1,n2,n3;
        boolean fin = false;

        try {
            fr = new FileReader(filenameTexto);
            br = new BufferedReader(fr);

            fis = new FileInputStream(filenameBinario);
            dis = new DataInputStream(fis);

            fw = new FileWriter(filenameFinal);
            bw = new BufferedWriter(fw);

         
            for (int i = 0; i < 100; i++) {
                n1 = br.read();
                n2 = dis.readInt();
                n3 = n1+n2;
                
                bw.write(n1+"+"+n2+"="+n3);
                bw.newLine();
                
            }
            
            
            

        } catch (EOFException ax) {
            fin = true;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ejercicio15.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ejercicio15.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(filenameFinal != null){
                bw.close();
                
                }
                if (fr != null) {
                  fr.close();
                }
            } catch (Exception e) {
            }
        
        
        }


    }//GEN-LAST:event_ruta3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelruta1;
    private javax.swing.JLabel labelruta2;
    private javax.swing.JLabel labelruta3;
    private javax.swing.JButton ruta1Button;
    private javax.swing.JButton ruta2Button;
    private javax.swing.JButton ruta3Button;
    // End of variables declaration//GEN-END:variables
}
