
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jose
 */
public class ventana extends javax.swing.JApplet {

    ArrayList<Estrella> listaEstrellas;

    static int ancho;
    static int alto;
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    
                    listaEstrellas=new ArrayList();
                    leerEstrellasDeFichero();
                    Timer timer = new Timer (100, new ActionListener ()
                    {
                        public void actionPerformed(ActionEvent e){
                           if (ancho==0){
                            ancho=panel.getWidth();
                            alto=panel.getHeight();
                           }
 
                            panel.getGraphics().clearRect(0, 0, panel.getWidth(), panel.getHeight());
                            for (Estrella es:listaEstrellas){
                                es.mover();                                
                                panel.getGraphics().drawOval(es.getX(), es.getY(), 5, 5);
                            }
                        }                                                
                    });
                    timer.start();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        masVelocidad = new javax.swing.JButton();
        menosVelocidad = new javax.swing.JButton();
        masEstrellas = new javax.swing.JButton();
        menosEstrellas = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        panel.setPreferredSize(new java.awt.Dimension(1000, 300));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        masVelocidad.setText("+ Velocidad");
        masVelocidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masVelocidadMouseClicked(evt);
            }
        });

        menosVelocidad.setText("- Velocidad");
        menosVelocidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosVelocidadMouseClicked(evt);
            }
        });

        masEstrellas.setText("+ Estrellas");
        masEstrellas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masEstrellasMouseClicked(evt);
            }
        });

        menosEstrellas.setText("- Estrellas");
        menosEstrellas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosEstrellasMouseClicked(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(masVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menosVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(masEstrellas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menosEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(guardar)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masVelocidad)
                            .addComponent(masEstrellas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menosVelocidad)
                            .addComponent(menosEstrellas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(guardar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void masEstrellasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEstrellasMouseClicked
        // TODO add your handling code here:
        Estrella e=new Estrella();
        listaEstrellas.add(e);
    }//GEN-LAST:event_masEstrellasMouseClicked

    private void menosEstrellasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEstrellasMouseClicked
        // TODO add your handling code here:
        if (listaEstrellas.size()>0)
            listaEstrellas.remove(0);
    }//GEN-LAST:event_menosEstrellasMouseClicked

    private void masVelocidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVelocidadMouseClicked
        // TODO add your handling code here:
        for (Estrella es:listaEstrellas)
            es.masVelocidad();
    }//GEN-LAST:event_masVelocidadMouseClicked

    private void menosVelocidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVelocidadMouseClicked
        // TODO add your handling code here:
        for (Estrella es:listaEstrellas)
            es.menosVelocidad();
    }//GEN-LAST:event_menosVelocidadMouseClicked
    private void leerEstrellasDeFichero(){
        File archivo;
        FileReader fr=null;
        BufferedReader br;
        try {
            archivo = new File ("estrellas.txt");        
            if (archivo.exists()){
                fr = new FileReader (archivo);
                br = new BufferedReader(fr);
        
                // Lectura del fichero
                String linea1,linea2,linea3,linea4;
                while((linea1=br.readLine())!=null){
                    linea2=br.readLine();
                    linea3=br.readLine();
                    linea4=br.readLine();
                    Estrella es=new Estrella(Integer.valueOf(linea1),Integer.valueOf(linea2),Integer.valueOf(linea3),Integer.valueOf(linea4));
                    listaEstrellas.add(es);
                }
            }
                } catch (Exception e){
                    System.out.println("Error al leer el archivo");
                } finally {
                    try {
                        fr.close();
                    } catch (Exception e){
                        System.out.println("Error al cerrar el archivo");
                    }
                }
        
    }
    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        // TODO add your handling code here:
        FileWriter fichero = null;
        BufferedWriter bw = null;
        try
        {
            fichero = new FileWriter("estrellas.txt");
            bw = new BufferedWriter(fichero);

            for (Estrella es:listaEstrellas){
                bw.write(String.valueOf(es.getX()));
                bw.newLine();
                bw.write(es.getY()+"");
                bw.newLine();
                bw.write(es.getVelocidadX()+"");
                bw.newLine();
                bw.write(es.getVelocidadY()+"");
                bw.newLine();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              bw.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_guardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar;
    private javax.swing.JButton masEstrellas;
    private javax.swing.JButton masVelocidad;
    private javax.swing.JButton menosEstrellas;
    private javax.swing.JButton menosVelocidad;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
