
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexk
 */
public class principal extends javax.swing.JFrame {

    ArrayList<Cliente> listaClientes;
    ArrayList<CuentaBancaria> listaCuentas;

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();

        Cliente Juan = new Cliente("Juan Martinez", "22.355.658-F");
        Cliente Pedro = new Cliente("Pedro Garrigos", "36.258.957-R");

        CuentaBancaria c1 = new CuentaBancaria("01234567890123456789", 250);
        CuentaBancaria c2 = new CuentaBancaria("98765432109876543210", 22500);

        CuentaBancaria c3 = new CuentaBancaria("65498732109873216540", 1200);
        CuentaBancaria c4 = new CuentaBancaria("78965412307896541230", 15000);
        CuentaBancaria c5 = new CuentaBancaria("45698712300321456987", 350);

        Juan.NuevaCuenta(c1);
        Juan.NuevaCuenta(c2);
        Pedro.NuevaCuenta(c3);
        Pedro.NuevaCuenta(c4);
        Pedro.NuevaCuenta(c5);

        listaClientes = new ArrayList();

        listaClientes.add(Juan);
        listaClientes.add(Pedro);

        DefaultListModel lCliente = new DefaultListModel();
        jListClientes.setModel(lCliente);

        for (int i = 0; i < listaClientes.size(); i++) {
            String c = listaClientes.get(i).getNombre() + "( " + listaClientes.get(i).getDni() + " )";
            lCliente.addElement(c);

        }

        /*   for (int i = 0; i < listaCuentas.size(); i++) {
            String c = listaCuentas.get(i).getNumero() +"   "+ listaCuentas.get(i).getSaldo();
            lCuentas.addElement(c);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCuentas = new javax.swing.JList<>();
        bIngreso = new javax.swing.JButton();
        bReintegro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clientes");

        jLabel2.setText("Cuentas");

        jListClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListClientes);

        jScrollPane2.setViewportView(jListCuentas);

        bIngreso.setText("Ingreso");
        bIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresoActionPerformed(evt);
            }
        });

        bReintegro.setText("Reintegro");
        bReintegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReintegroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bIngreso)
                        .addGap(33, 33, 33)
                        .addComponent(bReintegro))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bIngreso)
                    .addComponent(bReintegro))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClientesMouseClicked
        // TODO add your handling code here:

        Cliente c = listaClientes.get(jListClientes.getSelectedIndex());

        DefaultListModel lCuentas = new DefaultListModel();
        jListCuentas.setModel(lCuentas);

        for (int i = 0; i < c.ListaCuentas.size(); i++) {
            CuentaBancaria cb = c.ListaCuentas.get(i);
            lCuentas.addElement(cb.getNumero() + "   " + cb.getSaldo() + "€");
        }


    }//GEN-LAST:event_jListClientesMouseClicked

    private void bIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresoActionPerformed
        try {

            Cliente c = listaClientes.get(jListClientes.getSelectedIndex());
            CuentaBancaria cb = c.ListaCuentas.get(jListCuentas.getSelectedIndex());

            String Cantidad = JOptionPane.showInputDialog(this, "Cantidad a ingresar:");
            Double ingress = Double.parseDouble(Cantidad);

            cb.setIngreso(ingress);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No has seleccionado cliente o cuenta bancaria");
        }

//Alejandro ya obtienes el saldo correctamente te falta ya modificarlo con lo que te pida

    }//GEN-LAST:event_bIngresoActionPerformed

    private void bReintegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReintegroActionPerformed
        try {
            Cliente c = listaClientes.get(jListClientes.getSelectedIndex());
            CuentaBancaria cb = c.ListaCuentas.get(jListCuentas.getSelectedIndex());

            String Cantidad = JOptionPane.showInputDialog(this, "Cantidad a ingresar:");
            Double reingress = Double.parseDouble(Cantidad);

            cb.setReintegro(reingress);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No has seleccionado cliente o cuenta bancaria");
        }


    }//GEN-LAST:event_bReintegroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngreso;
    private javax.swing.JButton bReintegro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListCuentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
