/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a8 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        a10 = new javax.swing.JButton();
        a11 = new javax.swing.JButton();
        a12 = new javax.swing.JButton();
        a13 = new javax.swing.JButton();
        a14 = new javax.swing.JButton();
        a15 = new javax.swing.JButton();
        teclaQ = new javax.swing.JButton();
        teclaW = new javax.swing.JButton();
        teclaE = new javax.swing.JButton();
        teclaR = new javax.swing.JButton();
        teclaT = new javax.swing.JButton();
        teclaY = new javax.swing.JButton();
        teclaU = new javax.swing.JButton();
        teclaI = new javax.swing.JButton();
        teclaO = new javax.swing.JButton();
        teclaP = new javax.swing.JButton();
        teclaA = new javax.swing.JButton();
        teclaS = new javax.swing.JButton();
        teclaD = new javax.swing.JButton();
        teclaF = new javax.swing.JButton();
        teclaG = new javax.swing.JButton();
        teclaH = new javax.swing.JButton();
        teclaJ = new javax.swing.JButton();
        teclaK = new javax.swing.JButton();
        teclaL = new javax.swing.JButton();
        teclaZ = new javax.swing.JButton();
        teclaX = new javax.swing.JButton();
        teclaC = new javax.swing.JButton();
        teclaV = new javax.swing.JButton();
        teclaB = new javax.swing.JButton();
        teclaN = new javax.swing.JButton();
        teclaM = new javax.swing.JButton();

        a8.setText("A");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });

        a9.setText("A");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });

        a10.setText("A");
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });

        a11.setText("A");
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });

        a12.setText("A");
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });

        a13.setText("A");
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a13ActionPerformed(evt);
            }
        });

        a14.setText("A");
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a14ActionPerformed(evt);
            }
        });

        a15.setText("A");
        a15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a15ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teclaQ.setText("Q");
        teclaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaQActionPerformed(evt);
            }
        });

        teclaW.setText("W");
        teclaW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaWActionPerformed(evt);
            }
        });

        teclaE.setText("E");
        teclaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaEActionPerformed(evt);
            }
        });

        teclaR.setText("R");
        teclaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaRActionPerformed(evt);
            }
        });

        teclaT.setText("T");
        teclaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaTActionPerformed(evt);
            }
        });

        teclaY.setText("Y");
        teclaY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaYActionPerformed(evt);
            }
        });

        teclaU.setText("U");
        teclaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaUActionPerformed(evt);
            }
        });

        teclaI.setText("I");
        teclaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaIActionPerformed(evt);
            }
        });

        teclaO.setText("O");
        teclaO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaOActionPerformed(evt);
            }
        });

        teclaP.setText("P");
        teclaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaPActionPerformed(evt);
            }
        });

        teclaA.setText("A");
        teclaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaAActionPerformed(evt);
            }
        });

        teclaS.setText("S");
        teclaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaSActionPerformed(evt);
            }
        });

        teclaD.setText("D");
        teclaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaDActionPerformed(evt);
            }
        });

        teclaF.setText("F");
        teclaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaFActionPerformed(evt);
            }
        });

        teclaG.setText("G");
        teclaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaGActionPerformed(evt);
            }
        });

        teclaH.setText("H");
        teclaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaHActionPerformed(evt);
            }
        });

        teclaJ.setText("J");
        teclaJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaJActionPerformed(evt);
            }
        });

        teclaK.setText("K");
        teclaK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaKActionPerformed(evt);
            }
        });

        teclaL.setText("L");
        teclaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaLActionPerformed(evt);
            }
        });

        teclaZ.setText("Z");
        teclaZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaZActionPerformed(evt);
            }
        });

        teclaX.setText("X");
        teclaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaXActionPerformed(evt);
            }
        });

        teclaC.setText("C");
        teclaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaCActionPerformed(evt);
            }
        });

        teclaV.setText("V");
        teclaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaVActionPerformed(evt);
            }
        });

        teclaB.setText("B");
        teclaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaBActionPerformed(evt);
            }
        });

        teclaN.setText("N");
        teclaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaNActionPerformed(evt);
            }
        });

        teclaM.setText("M");
        teclaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teclaMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teclaQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(teclaA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teclaK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teclaL)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(teclaZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teclaX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teclaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teclaV)
                .addGap(18, 18, 18)
                .addComponent(teclaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teclaN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teclaM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclaQ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaW, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclaA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teclaZ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teclaM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teclaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaQActionPerformed

    private void teclaWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaWActionPerformed

    private void teclaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaEActionPerformed

    private void teclaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaRActionPerformed

    private void teclaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaTActionPerformed

    private void teclaYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaYActionPerformed

    private void teclaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaUActionPerformed

    private void teclaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaIActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a9ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a10ActionPerformed

    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a11ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a12ActionPerformed

    private void a13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a13ActionPerformed

    private void a14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a14ActionPerformed

    private void a15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a15ActionPerformed

    private void teclaOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaOActionPerformed

    private void teclaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaPActionPerformed

    private void teclaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaAActionPerformed

    private void teclaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaSActionPerformed

    private void teclaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaDActionPerformed

    private void teclaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaFActionPerformed

    private void teclaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaGActionPerformed

    private void teclaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaHActionPerformed

    private void teclaJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaJActionPerformed

    private void teclaKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaKActionPerformed

    private void teclaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaLActionPerformed

    private void teclaZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaZActionPerformed

    private void teclaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaXActionPerformed

    private void teclaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaCActionPerformed

    private void teclaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaVActionPerformed

    private void teclaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaBActionPerformed

    private void teclaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaNActionPerformed

    private void teclaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teclaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teclaMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a10;
    private javax.swing.JButton a11;
    private javax.swing.JButton a12;
    private javax.swing.JButton a13;
    private javax.swing.JButton a14;
    private javax.swing.JButton a15;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private javax.swing.JButton teclaA;
    private javax.swing.JButton teclaB;
    private javax.swing.JButton teclaC;
    private javax.swing.JButton teclaD;
    private javax.swing.JButton teclaE;
    private javax.swing.JButton teclaF;
    private javax.swing.JButton teclaG;
    private javax.swing.JButton teclaH;
    private javax.swing.JButton teclaI;
    private javax.swing.JButton teclaJ;
    private javax.swing.JButton teclaK;
    private javax.swing.JButton teclaL;
    private javax.swing.JButton teclaM;
    private javax.swing.JButton teclaN;
    private javax.swing.JButton teclaO;
    private javax.swing.JButton teclaP;
    private javax.swing.JButton teclaQ;
    private javax.swing.JButton teclaR;
    private javax.swing.JButton teclaS;
    private javax.swing.JButton teclaT;
    private javax.swing.JButton teclaU;
    private javax.swing.JButton teclaV;
    private javax.swing.JButton teclaW;
    private javax.swing.JButton teclaX;
    private javax.swing.JButton teclaY;
    private javax.swing.JButton teclaZ;
    // End of variables declaration//GEN-END:variables
}
