
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.tools.FileObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alexk
 */
public class principal extends javax.swing.JFrame {

    ArrayList<Persona> ListaPersonas = new ArrayList();

    DefaultListModel lm = new DefaultListModel();

    public principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonAnadir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        textoNIF = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        textoProfesion = new javax.swing.JTextField();
        textoEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaGrafico = new javax.swing.JList<>();
        guardarTxt = new javax.swing.JButton();
        leerTxt = new javax.swing.JButton();
        guardarSerie = new javax.swing.JButton();
        leerSerie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIF");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Profesión");

        jLabel5.setText("Edad");

        botonAnadir.setText("Añadir");
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        ListaGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaGraficoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaGrafico);

        guardarTxt.setText("Guardar txt");
        guardarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTxtActionPerformed(evt);
            }
        });

        leerTxt.setText("Leer txt");
        leerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerTxtActionPerformed(evt);
            }
        });

        guardarSerie.setText("Guardar serie");
        guardarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarSerieActionPerformed(evt);
            }
        });

        leerSerie.setText("Leer serie");
        leerSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoNIF)
                            .addComponent(textoNombre)
                            .addComponent(textoApellidos)
                            .addComponent(textoProfesion)
                            .addComponent(textoEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAnadir)
                            .addComponent(botonEliminar))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarTxt)
                            .addComponent(guardarSerie))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leerSerie)
                            .addComponent(leerTxt))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textoNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonAnadir))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(botonEliminar)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarTxt)
                    .addComponent(leerTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarSerie)
                    .addComponent(leerSerie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTxtActionPerformed
        FileWriter fw = null;
        BufferedWriter bw = null;
        String fichero = guardarDialogo();

        try {
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < ListaPersonas.size(); i++) {

                bw.write(ListaPersonas.get(i).getNif());
                bw.newLine();
                bw.write(ListaPersonas.get(i).getNombre());
                bw.newLine();
                bw.write(ListaPersonas.get(i).getApellidos());
                bw.newLine();
                bw.write(ListaPersonas.get(i).getProfesion());
                bw.newLine();
                bw.write("" + ListaPersonas.get(i).getEdad());
                bw.newLine();

            }

        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            if (fichero != null) {
                try {
                    bw.close();
                } catch (IOException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }


    }//GEN-LAST:event_guardarTxtActionPerformed

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed

        Persona nuevaPersona = new Persona();
        nuevaPersona.setNif(textoNIF.getText());
        nuevaPersona.setNombre(textoNombre.getText());
        nuevaPersona.setApellidos(textoApellidos.getText());
        nuevaPersona.setProfesion(textoProfesion.getText());
        if (!textoEdad.getText().equals("")) {
            nuevaPersona.setEdad(Integer.parseInt(textoEdad.getText()));
        }

        ListaPersonas.add(nuevaPersona);
        ListaGrafico.setModel(lm);

        lm.addElement(nuevaPersona.toString());


    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed

        if (ListaGrafico.getSelectedIndex() == -1) {
            System.out.println("No has seleccionado ningun indice");
        } else {
            int indice = ListaGrafico.getSelectedIndex();
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION) == 0) {

                ListaPersonas.remove(indice);

                lm.remove(indice);

            }

        }


    }//GEN-LAST:event_botonEliminarActionPerformed

    private void leerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerTxtActionPerformed
        try {
            lm.removeAllElements();
            ListaPersonas.removeAll(ListaPersonas);

            FileReader fr = null;
            BufferedReader br = null;
            String fichero = cargarDialogo();

            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
            String linea;
            String nif = "";
            String nombre = "";
            String apellidos = "";
            String profesion = "";
            String edad = "";
            int edadN = 0;

            while ((linea = br.readLine()) != null) {

                nif = linea;
                nombre = br.readLine();
                apellidos = br.readLine();
                profesion = br.readLine();
                edad = br.readLine();
                edadN = Integer.parseInt(edad);

                Persona p = new Persona(nif, nombre, apellidos, profesion, edadN);
                ListaPersonas.add(p);

            }
            ListaGrafico.setModel(lm);
            for (int i = 0; i < ListaPersonas.size(); i++) {
                lm.addElement(ListaPersonas.get(i).toString());
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_leerTxtActionPerformed

    private void guardarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarSerieActionPerformed
        String fichero = guardarDialogo();

        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fichero));

            for (int i = 0; i < ListaPersonas.size(); i++) {
                Persona p = ListaPersonas.get(i);
                oos.writeObject(p);

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_guardarSerieActionPerformed

    private void leerSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerSerieActionPerformed
        lm.removeAllElements();
        ListaPersonas.removeAll(ListaPersonas);

        String fichero = cargarDialogo();
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fichero));
            ListaGrafico.setModel(lm);

            while (ois.readObject() != null) {
                lm.addElement(ois.readObject());

            }

        } catch (EOFException ax) {
            System.out.println("Fin fichero");
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_leerSerieActionPerformed

    private void ListaGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaGraficoMouseClicked
        
        int indice = ListaGrafico.getSelectedIndex();
        
        textoNIF.setText(ListaPersonas.get(indice).getNif());
        textoNombre.setText(ListaPersonas.get(indice).getNombre());
        textoApellidos.setText(ListaPersonas.get(indice).getApellidos());
        textoProfesion.setText(ListaPersonas.get(indice).getProfesion());
        textoEdad.setText(""+ListaPersonas.get(indice).getEdad());
        
        
        
    }//GEN-LAST:event_ListaGraficoMouseClicked

    public String guardarDialogo() {

        FileDialog fd = new FileDialog(this, "Elije un Fichero", FileDialog.SAVE);
        fd.setDirectory("C:\\temp"); //Opcional
        fd.setFile("*.txt"); //Opcional
        fd.setVisible(true);
        String filename = fd.getDirectory() + "/" + fd.getFile();
        if (fd.getFile() == null) {
            System.out.println("No has seleccionado ningún fichero");
        } else {
            System.out.println("El fichero seleccionado es: " + filename);

        }

        return filename;

    }

    public String cargarDialogo() {
        FileDialog fd = new FileDialog(this, "Elije un Fichero", FileDialog.LOAD);
        fd.setDirectory("C:\\temp"); //Opcional
        fd.setFile("*.txt"); //Opcional
        fd.setVisible(true);
        String filename = fd.getDirectory() + "/" + fd.getFile();
        if (fd.getFile() == null) {
            System.out.println("No has seleccionado ningún fichero");
        } else {
            System.out.println("El fichero seleccionado es: " + filename);

        }

        return filename;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaGrafico;
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton guardarSerie;
    private javax.swing.JButton guardarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leerSerie;
    private javax.swing.JButton leerTxt;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoEdad;
    private javax.swing.JTextField textoNIF;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoProfesion;
    // End of variables declaration//GEN-END:variables
}
